### ISSUE TITLE
Homepage: Email icon at top of pages goes to the Mailing list instead of to an OPeNDAP email address

### ISSUE THREAD

**Issue by ndp-opendap** [OPENDAP/Website#1]
the description

**Comment by ndp-opendap** [comment]
Imported draft to Website test

**Comment by Arika-V** [comment]
## description

The mail sign at the top of the pages goes to the OPeNDAP mailing list (https://groups.google.com/a/opendap.org/g/opendap). Typically, I think that's the sign for writing an email to the org (e.g., support@opendap.com)? So it's a little confusing. I would suggest either A) changing that icon to represent a mailing list or B) changing the link to be support@

![Image](https://github.com/OPENDAP/bes/assets/170548569/da3d3a05-d7ce-4243-8a2b-ceb569c0a810)

**Comment by Mikejmnez** [comment]
Hey @jahattox - I tried updating the site by setting the icon described above to go to the support email. I did:

1. Went to Theme settings, Header and scrolled to Utility Menu  
2.  I replace the previous URL with  mailto:support@opendap.com but the site builder tells me this is an Invalid URL. 

<img width="500" alt="Screenshot 2024-05-23 at 11.03.33 PM" src="https://github.com/OPENDAP/Website/assets/8241481/7a719706-a8cd-41be-909c-83aeb78bf000">



Any suggestions?

**Comment by jahattox** [comment]
@Mikejmnez This should be fixed now

**Comment by Mikejmnez** [comment]
Thank you @jahattox! The url on the Menuy header is fixed indeed. I just noticed that the email icon on the Footer also needs to be fixed. I will look at your approach and try to do the same with the footer. I will report back if I am able to do this.

**Comment by Mikejmnez** [comment]
Fixed on the Footer :)
