### ISSUE TITLE
Footer: Documentation link is incorrect

### ISSUE THREAD

**Issue by Arika-V** [OPENDAP/Website#10]
This issue refers to the Documentation link in the footer here: 

https://newopendap.flywheelsites.com/

![Image](https://github.com/OPENDAP/Website/assets/170548569/00a9cbef-2d1f-4170-86b3-d84acb60987a)

**Comment by Mikejmnez** [comment]
I made the change :). It should go now to the Documentation

**Comment by Mikejmnez** [comment]
@jgallagher59701 this

**Comment by jgallagher59701** [comment]
Done
