### ISSUE TITLE
Homepage: "About the team" link goes to "About" page instead

### ISSUE THREAD

**Issue by Arika-V** [OPENDAP/Website#12]
https://newopendap.flywheelsites.com/

![Image](https://github.com/OPENDAP/Website/assets/170548569/1a91f670-15e3-4cb7-b03a-9999a9f02756)

**Comment by Mikejmnez** [comment]
I went to the website admit page, and made the correction. Clicking on "About the team" no longer goes to "About", and it correctly takes you to the "About the Team" page.

**Comment by Mikejmnez** [comment]
@jgallagher59701 this

**Comment by jgallagher59701** [comment]
Thanks!
