### ISSUE TITLE
Homepage: Change Australia Government link

### ISSUE THREAD

**Issue by Arika-V** [OPENDAP/Website#14]
Change the link to http://www.bom.gov.au/ 

https://newopendap.flywheelsites.com/

![Image](https://github.com/OPENDAP/Website/assets/170548569/b2043de5-424d-44cc-825a-762c790cd4fc)

**Comment by Mikejmnez** [comment]
I took a look at this. I clicked on the Icon and it took me to the page http://www.bom.gov.au/, which is the one is being suggested in this issue. 

Since the behavior I experience is the one being suggested, I will mark this as done and move it to done.
