### ISSUE TITLE
Decision/further info about a subpage: online-help-files

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#15]
### Description

This subpage is a little hard to understand: there is a lot of text and little information about a `dataURL box`. In particular:
* If this approach still being used/ useful? 
* Is this page really necessary?
* Should it be instead a tutorial/video/blog?

### Visual Aid
<img width="400" alt="Screenshot 2024-05-23 at 9 56 43 AM" src="https://github.com/OPENDAP/Website/assets/8241481/1b9e09c7-1002-4437-8ac5-68ea20f61ed9">

### Page URL 
Here is the original page: https://www.opendap.org/support/online-help-files
The new page can be found: HOMEPAGE/support/online-help-files/

**Comment by Mikejmnez** [comment]
@jgallagher59701 I am leaning towards not including this new subpage on the new website. Is that OK? Unless you think it is  of some help.

**Comment by jgallagher59701** [comment]
I agree. In deed, that page is old and some of the specific details are wrong. 

We probably do need some sort of help for the form interface, but it should be part of the form itself and not the website.

**Comment by Mikejmnez** [comment]
Great. I have removed this option but the subpage is now hidden (private). We can later go back to it with time, and make it more useful for later purposes

**Comment by ndp-opendap** [comment]
This solution is not OK.

Every Hyrax instance in the world creates links to this page. 

The links are part of the DAP2/DAP4 Data Request Form pages that the Hyrax service builds for every single dataset. 

PLEASE, let's find a solution that does not break tens of thousands of links.

Example: http://test.opendap.org:8080/opendap/data/nc/fnoc1.nc.dmr.html

In the left hand column those links all point to online-help-files content.

**Comment by ndp-opendap** [comment]
> If this approach still being used/useful?

YES.
> Is this page really necessary?

YES
> Should it be instead a tutorial/video/blog?

Maybe but given that it is in use as the source of descriptive help for the Hyrax Data Request Form service we should correct its deficiencies and preserve it's current URL ()or at least make it a redirect).

**Comment by Mikejmnez** [comment]
Oh I was not aware of this - thanks @ndp-opendap !! I will revert the change I made i.e. make the subpage available again (note -- this is for the website that is not live yet - so no changes have been made to the 'live' website). 

These are the changes that need to happen to the subpage


- [x] Rename the title of subpage to Glossary of terms in DAP Response Form. It is self-explanatory. Note that the url does not need to change.
- [x] Under **General Help **- show how to get a DAP Response Form for a (test) file.
- [x] Add a screenshot of the DAP Response Form associated with a specific file, say the same as above.
- [x] Make the items of the subpage match the items on the DAP Response Form (Disposition does not appear on the DAP Response Form). For example: http://test.opendap.org/dap/data/nc/coads_climatology.nc.dmr. And improve the descriptions.

**Comment by Mikejmnez** [comment]
I worked on this. Feel OK about it. @jgallagher59701  ready for review. You can find the subpage [here](https://newopendap.flywheelsites.com/support/online-help-files/)

**Comment by jgallagher59701** [comment]
The site now asks me to sign in. I wonder if this is because I made the account, etc.

**Comment by jgallagher59701** [comment]
My password for the "flywheel sites" site does not work on https://newopendap.flywheelsites.com/

**Comment by Mikejmnez** [comment]
> My password for the "flywheel sites" site does not work on https://newopendap.flywheelsites.com/

The Pixel Lighthouse team changed the URL. This is the new one: http://opendap.flywheelsites.com/

**Comment by jgallagher59701** [comment]
On this page https://opendap.flywheelsites.com/software/hyrax-data-server/ I think we should modify this paragraph: 
_Hyrax is a data server developed by OPeNDAP. If you have data that you’d like to be made accessible by the OPeNDAP protocol, you’ll need to download the Hyrax data server or a server from one of [our partners](https://opendap.flywheelsites.com/software/interoperability/#single_column_content-6)._

So that it's ore obvious that people can download our server further down on the page. Maybe a link from _the Hyrax data server_ to the place down the page where that is discussed/

**Comment by Mikejmnez** [comment]
@jgallagher59701 
How about the contents of this page: https://opendap.flywheelsites.com/support/online-help-files/?

**Comment by jgallagher59701** [comment]
This looks good. But see #39 because links are baked into the web form and we need those to work. We can update the new code, of course, but old servers will be run for years. So we should make sure the links with anchors like the on in issue #39 still work.

**Comment by Mikejmnez** [comment]
Ok, I see. This should be an easy fix!

**Comment by jgallagher59701** [comment]
The page is back and it works, so lets close this. However, the way the anchors work seems broken to me - I will follow up in #39.
