### ISSUE TITLE
In the 'Stats' part of the top page, the inside of the 'nebula' says "Open Source Make Discovery Possible." No. We need to fix that.

### ISSUE THREAD

**Issue by jgallagher59701** [OPENDAP/Website#16]

**Comment by Mikejmnez** [comment]
How about:
1) Open Data Access Accelerates Discovery.
2) Open Data Access accelerates scientific discovery.
3) Open and Equitable Data Access accelerate discovery.
4) Promoting Open Data Access in the Era of Data-Driven Discovery.
5) Open Data Access Drives Equitable and Reproducible Discovery.
6) Open Data Access accelerates discovery and lowers technological barriers.

@jgallagher59701  I updated with website with option 1) above: short and concise. But other possibilities exists.

**Comment by jgallagher59701** [comment]
I think #1 is good - concise and gets to the idea that we are about more than just a particular piece of software.

**Comment by Mikejmnez** [comment]
Great! I thought it was a good fit for us too
