### ISSUE TITLE
On the 'About OPeNDP' page, the image at the top right of the page doesn't make much sense. I think it's Jupiter (maybe Neptune?). Regardless, we need a more appropriate image.

### ISSUE THREAD

**Issue by jgallagher59701** [OPENDAP/Website#17]

**Comment by Mikejmnez** [comment]
Yeah, that makes sense - i think all these are just templates until we find something that fits OPeNDAP better. I can search for some stock photos on [NASA's Earth Observatory](https://earthobservatory.nasa.gov/). Or, do you have something in mind?

**Comment by Mikejmnez** [comment]
I made a list of some options I found for various parts of the website (these are all from NASA's Earth Observatory, but I can certainly look for some other sources of images). These may be too visually striking, perhaps for the website, but worth considering.

1) [Volcanoes](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152839/harratkhaybar_oli2_20240425_lrg.jpg).
2) Wilkins [Ice Shelf](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152653/wilkinsiceshelf_tmo_20240124_lrg.jpg)
3) [Moose River](https://eoimages.gsfc.nasa.gov/images/imagerecords/144000/144461/iss057e115019_lrg.jpg)
4) [Solar Eclipse](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152663/totalsolareclipse_epc_20240408_lrg.jpg) over North America
5) [Houston Blackout](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152843/houstontx_bmhd_20240518_lrg.jpg)  (fractal looking!)
6) [Phytoplankton bloom](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152765/oman_pace_20240317_lrg.jpg) image from PACE.
7) [Aurora borealis](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152587/iss070e051709_lrg.jpg) from space
8) Siachen [Glacier](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152572/ISS069-E-60266_lrg.jpg).
9) East Greenland Glacier [here](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152557/piday_tm5_19860906_lrg.jpg)  and [here 6 years later](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152557/piday_oli_20230912_lrg.jpg).
10) [ Elephant movement](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152542/animalbornesensors_elephants_2008_lrg.jpg) across Kruger Natl. Part over 1 year.
11) [Rivers and Tributaries](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152452/vlmcharleston_se1_2020_lrg.jpg) over South Carolina near the Atlantic Ocean.
12) [Evening glow](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152456/iss069e016826_lrg.jpg) over Junggar Basin.
13) [Ice Swirls](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152440/labrador_seaice_tmo_20240203_lrg.jpg) along Labrador Coast.
14) [Las Vegas](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152421/iss067e369057_lrg.jpg) lights.
15) [Phytoplankton bloom](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152424/austbloom_oli2_20240121_lrg.jpg) along edges of unstable ocean flows
16) [Sunrise](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152259/ISS070-E-1178z_lrg.JPG) from the ISS.
17) Another [Aurora Borealis](https://eoimages.gsfc.nasa.gov/images/imagerecords/147000/147984/iss053e023965_lrg.jpg) from Space.
18) (Fractal) [rivers and valleys](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152262/ISS070-E-34898_lrg.jpg) of the upper Mississippii
19) One more [Aurora Borealis](https://eoimages.gsfc.nasa.gov/images/imagerecords/152000/152217/bcaurora_vir_2023351_lrg.jpg) shot.




I can update the page one of the photos above and test how they look

**Comment by Mikejmnez** [comment]
I will also spend some time looking at other Non-satellite stock images elsewhere

**Comment by Mikejmnez** [comment]
I created a new image [see here](https://newopendap.flywheelsites.com/about/). @jgallagher59701 let me know what you think!

**Comment by jgallagher59701** [comment]
That's pretty good - lets go with it.
My take is that we might want to move away from the generic images as time goes on, but I'd really like to get the site up.

**Comment by jgallagher59701** [comment]
Whoops, maybe you should close this if there's some other action that needs to be done. Else, feel free to close it.

**Comment by Mikejmnez** [comment]
> That's pretty good - lets go with it. My take is that we might want to move away from the generic images as time goes on, but I'd really like to get the site up.

I completely agree - I think with time we will be able to get better images.
