### ISSUE TITLE
Christine never gave he permission for a photo of her to appear. We should remove that and if we really want one, pester her more. But, lets me careful because NASA people are hard to get these testimonials from so we don't want to scare her away.

### ISSUE THREAD

**Issue by jgallagher59701** [OPENDAP/Website#18]

**Comment by Mikejmnez** [comment]
Wow. I assume she did since we have that photo. @jgallagher59701 can you reach back to her to ask for her consent for the use of the photo we have (which I don't know how we have it), or any other photo she wishes to make available? Otherwise, we may consider two options:

1) Not include her testimony.
2) Include her testimony with an template image but not avatar.

**Comment by jgallagher59701** [comment]
What if we do what ESIP did for the testimonials without pictures?
<img width="1019" alt="Screenshot 2024-06-10 at 16 23 09" src="https://github.com/OPENDAP/Website/assets/8326698/4c8556bb-0999-4eee-9d08-bf10cdbe4f47">

**Comment by Mikejmnez** [comment]
Done @jgallagher59701 . I have removed all photos from the testimonials. You can check it now [here](https://newopendap.flywheelsites.com/use-cases/access-data/).

**Comment by jgallagher59701** [comment]
That does make it uniform. We could have some with and some without pictures. That's what is actually done on the ESIP site. If the people sent us pictures, that would be OK. Maybe I should bug Christine to send us a picture? 

Sorry to go back and forth on this.

**Comment by Mikejmnez** [comment]
No problem. I will put the other photos back. I think that it couldn't hurt to ask her if she would be open to have a photo of her, and what photo she'd find appropriate.

**Comment by Mikejmnez** [comment]
@jgallagher59701  Did you end up asking for Christine's photo?

**Comment by jgallagher59701** [comment]
I was just looking for that. That is, her slack info.

**Comment by jgallagher59701** [comment]
Asked

**Comment by jgallagher59701** [comment]
She asked to not have a picture.
I think we should close this issue - some people don't want that.

**Comment by Mikejmnez** [comment]
OK -- I am putting Malte and Bridget's photos back. I am also closing this issue.
