### ISSUE TITLE
replace Panoply with Panoply Data Viewer

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#19]
### Description

Panoply is also some form of database software. see [here](https://panoply.io/why-panoply/). The link on the OPeNDAP website correctly takes you to NASA's GISS website where they actually refer it to as "Panoply Data Viewer". And so I think we should be consistent with that.

Also, we should replace: `Machintosh` with `macOS` or `OSX` in the description of `Panoply Data Viewer`.

### visual aid
<img width="633" alt="sample" src="https://github.com/OPENDAP/Website/assets/8241481/5bccd457-0959-4e17-80da-9e6bee75168e">

### Page URL 

HOMEPAGE/software/software-from-other-sources/

**Comment by jgallagher59701** [comment]
I think calling panoply data viewer with a link to the NASA page is the correct thing to do.

**Comment by Mikejmnez** [comment]
Great! I have already made the change if you want to try to test it. Otherwise we can mask this as completed
