### ISSUE TITLE
On the Presentations subpage, the page selection numbers don't work as expected.

### ISSUE THREAD

**Issue by Arika-V** [OPENDAP/Website#2]
### Description of the problem
When I goto the pages (in red) at the bottom of the page and click on '50,' for example, nothing happens. Clicking the 'next page arrow works. I think none of the numbers work until that page has been displayed using the 'next page' arrows.

### PageURL
HOMEPAGE/community/presentations/

### Image
![Image](https://github.com/OPENDAP/Website/assets/8326698/c1a05d89-7d6f-4c04-a936-b3450d484169)

**Comment by Mikejmnez** [comment]
@jgallagher59701 

I gave it a try and they work for me. Is this still an issue?

Selecting the `50` icon works, but there is no content. In fact, the last Zenodo page with content is 15.

**Comment by jgallagher59701** [comment]
I think Pixel lighthouse has to fix this one. Or, we need to get familiar with the zenodo plugin.

**Comment by jahattox** [comment]
This should be fixed now. How do things look on your end?

**Comment by Mikejmnez** [comment]
Thanks @jahattox. Navigating from page 1 to page 15 works well for me. No additional (empty) pages are available for navigation.

@jgallagher59701 It works on my end, how does it look to you?

**Comment by jgallagher59701** [comment]
This fixes the issue reported. But the list of documents from zenodo is pretty hard to use. For example, how to I search it? Is there a way to get the documents to appear is chronological order?

**Comment by jgallagher59701** [comment]
Oh, I see the chronological ordering is an issue in progress.
