### ISSUE TITLE
update description of opendapr

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#20]
### Description

The current link to `opendapr` is broken. There is a new one [here](https://rdrr.io/github/ptaconet/opendapr/). However, it has been renamed to `modisfast` and so we should reference to it as such. The official documentation for it is: https://ptaconet.github.io/modisfast/

### Page URL 

HOMEPAGE/software/software-from-other-sources/

**Comment by jgallagher59701** [comment]
I think we should call it modisfast and maybe put 'formally opendapr' in parens.

**Comment by Mikejmnez** [comment]
Ok, done! I will mark this as completed then
