### ISSUE TITLE
Add more software libraries that can be used to access OPeNDAP servers

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#21]
### Description
The ones that immediately come to mind are: `xarray`, `pyFerret`, `Intake` catalogs, and potentially `Virtualizarr`, but that last one maybe indirectly?

### Page URL 

[HOMEPAGE/software/interoperability/](https://newopendap.flywheelsites.com/software/interoperability/)

**Comment by Mikejmnez** [comment]
I added PyFerret and xarray. I think we can wait on virtualizarr

**Comment by jgallagher59701** [comment]
Agreed, wait on VirtualiZarr.

**Comment by Mikejmnez** [comment]
Done.
