### ISSUE TITLE
Rename `Software from other sources` subpage to 'Interoperability'

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#22]
### Description
The subpage is called "Software from other sources", and the tab/link that takes you to this page is called 'Supported Software', under `SOFTWARE` menu. The problem I find is that:
1. The tab name under the SOFTWARE menu and the title of the subpage DO NOT MATCH.
2. Both are too verbose.
3. Not self explanatory.

Instead, I propose to use `Interoperability` in both the tab under the SOFTWARE menu, and the title of the subpage. `Interoperability` is self-explanatory, and less verbose.

### Visual Aid
 - **Current Behavior**

<img width="450" alt="Screenshot 2024-06-17 at 1 10 15 PM" src="https://github.com/OPENDAP/Website/assets/8241481/847a47de-ae4f-412e-be7d-67a3da0301bd">

### Page URL 

* **OLD_WEBSITE**:  https://www.opendap.org/allsoftware/other-sources

* **NEW_WEBSITE URL**: HOMEPAGE/software/software-from-other-sources/

**Comment by jgallagher59701** [comment]
OK. That sounds like a good change.

**Comment by Mikejmnez** [comment]
Done. I will close this then, as completed
