### ISSUE TITLE
Remove testimonial from OPeNDAP/UseCases/Developers

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#25]
### Description

Testimonials are meant to be visible only the Carousel at Access Data. However, Christine's testimonial shows up in Developers,  outside of any carousel, and without any of the other testimonials. That is clearly a bug.

### Visual Aid

<img width="553" alt="Screenshot 2024-06-18 at 4 56 13 PM" src="https://github.com/OPENDAP/Website/assets/8241481/59cb1d5d-ffc8-4a0d-ae94-90afc3161fe1">

### url
[HOMEPAGE/use-cases/developers](https://newopendap.flywheelsites.com/use-cases/developers/)

**Comment by Mikejmnez** [comment]
@jgallagher59701 ready for review

**Comment by jgallagher59701** [comment]
Thanks!
