### ISSUE TITLE
Presentations should be chronologically ordered

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#3]
### Brief description
Presentations from Zenodo look great! However, these are not arranged chronologically and that can cause some confusion. 

### Visual Aid
<img width="500" alt="Screenshot 2024-05-22 at 11 10 24 AM" src="https://github.com/OPENDAP/Website/assets/8241481/caf184f6-06f8-4982-9477-8c5b80a30266">

### Page URL

* HOMEPAGE/community/presentations/?zenodo_page=1

**Comment by Mikejmnez** [comment]
The same issue shows up in the community page:

<img width="300" alt="Screenshot 2024-05-23 at 8 36 18 AM" src="https://github.com/OPENDAP/Website/assets/8241481/aaef31e9-0471-4e81-8c07-34178fd8a4c9">

**Comment by Mikejmnez** [comment]
@jahattox I couldn't figure out how to do this on the site builder. Do you think this is possible to set up?

**Comment by jahattox** [comment]
@Mikejmnez I'm wondering if this is a limitation of the Zenodo API. Here's the docs: https://developers.zenodo.org/#list

And here's the API call the plugin uses: https://zenodo.org/api/records/?sort=mostrecent

Could it be that "mostrecent" means the most recently uploaded, rather than ordering by publication date? I tried reversing the sort as well, and it updates, but it still isn't ordered by the year.

**Comment by ndp-opendap** [comment]
> Could it be that "mostrecent" means the most recently uploaded, rather than ordering by publication date? I tried reversing the sort as well, and it updates, but it still isn't ordered by the year.

That's what it means I think.

**Comment by Mikejmnez** [comment]
> @Mikejmnez I'm wondering if this is a limitation of the Zenodo API. Here's the docs: https://developers.zenodo.org/#list
> 
> And here's the API call the plugin uses: https://zenodo.org/api/records/?sort=mostrecent
> 
> Could it be that "mostrecent" means the most recently uploaded, rather than ordering by publication date? I tried reversing the sort as well, and it updates, but it still isn't ordered by the year.

I see. Then perhaps the solution would be to (manually) modify these presentations (get a new version of the presentation that is) so that sorting these result in a chronological order arrangement...

**Comment by Mikejmnez** [comment]
@jahattox I finally had some time to look into this. Zenodo has several ways of sorting the records, and one of them is `Published[newest]`. That is what we want ([see here](https://zenodo.org/communities/opendap/records?q=&l=list&p=1&s=10&sort=publication-desc)). By looking at the sorting key what we want is: 

```python
{'sort':'publication-desc'}
```

I quickly ran  in a ipython shell and 

```python
community_id = 'opendap'
url = f'https://zenodo.org/api/records'
params = {
    'communities': community_id,
    'page': 1,
    'sort': 'publication-desc',
    'size': 10  # Number of records per page (maximum is 100)
}
response = requests.get(url, params=params)
data = response.json()
```
and looking at the data, something like this should work...

**Comment by jahattox** [comment]
@Mikejmnez Nice! That seems to have done the trick. I just pushed up the change. How do things look on your end?

**Comment by Mikejmnez** [comment]
@jahattox they look great! marking this as completed :)
