### ISSUE TITLE
On Why OPeNDAP - replace Open Science with something more appropriate

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#31]
### Description

Replace sentence "Want to be part of Open Science?" with

1. "What to enable Data Democratization?"
2. "Want to be part of enabling data-driven discovery?"
3. "Want to be part of Open Data Access?"

### Visual Aid

![Screenshot 2024-07-01 at 1 55 47 PM](https://github.com/OPENDAP/Website/assets/8241481/7c9ccf67-2c83-4ab0-b523-55120fc64d5c)

### Page URL 

https://www.opendap.org/about/why-opendap/

**Comment by Mikejmnez** [comment]
@jgallagher59701 which one sounds better?

**Comment by jgallagher59701** [comment]
I think number 3

**Comment by jgallagher59701** [comment]
Done. Thanks.
