### ISSUE TITLE
support menu option leads to a page redirect problem

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#33]
### Description

I am testing the website (links, documentation, etc). I noticed that when I click on the Menu 'Support' option on the menu, I get an error loading the page. This button should redirect to the Subpage Support.

### Visual Aid

<img width="450" alt="Screenshot 2024-07-01 at 3 59 07 PM" src="https://github.com/OPENDAP/Website/assets/8241481/f241d30c-d9d8-4974-a6fa-e729be955a9a">

### Page URL 

https://www.opendap.org/support/

**Comment by Mikejmnez** [comment]
I can successfully preview the support subpage from within Wordpress Admin:

<img width="500" alt="Screenshot 2024-07-01 at 4 09 02 PM" src="https://github.com/OPENDAP/Website/assets/8241481/7b049054-c245-49b5-8f74-e301645552d9">

**Comment by Mikejmnez** [comment]
Anybody else has the same problem?

**Comment by Mikejmnez** [comment]
This seems to be a persistent issue. @jahattox can you help us here? I can preview the page from the WP-admin dashboard just fine, but we cannot navigate from within the website. Thanks!

**Comment by jahattox** [comment]
@Mikejmnez Looks like one of the redirects (found under Settings > Redirection) was causing a redirect loop. I disabled it and the page seems to load normally now. Are you able to access the page?

**Comment by ndp-opendap** [comment]
Works for me!!

**Comment by Mikejmnez** [comment]
works for me too, thanks @jahattox !
