### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#34]
### Description

On the page [What is OPeNDAP](https://www.opendap.org/about/what-is-opendap/), the Documentation button inside "Get Started with OPeNDAP" leads to a Page Not Found

### Visual Aid

<img width="450" alt="Screenshot 2024-07-01 at 4 34 25 PM" src="https://github.com/OPENDAP/Website/assets/8241481/4d9a226f-73c4-447f-b328-48bb5a5450ea">

**Comment by Mikejmnez** [comment]
Done. Now:
1. Documentation takes you to the Official Ascii documentation, and
2. Starter Guides takes you to the Quick Start Guide, as described in the text. It could also take you to Support (where there are also links to the documentation, tutorials, FAQs, etc). However, I am having trouble with that page (see #33 )

**Comment by jgallagher59701** [comment]
Done
