### ISSUE TITLE
Clarify that OPeNDAP is not only useful for the scientific community

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#45]
### Description

The text (see below) makes it sound like OPeNDAP is only useful for scientists.

### Visual Aid

![Screenshot 2024-08-19 at 11 53 35 AM](https://github.com/user-attachments/assets/3d0c203e-9c55-49bf-a224-640d0dbc7fa9)

### Page URL 
[homepage](https://www.opendap.org/)

**Comment by Mikejmnez** [comment]
I am leaning to greatly reduce the text to the following (preview)

![Image](https://github.com/user-attachments/assets/b6da7331-4af4-433d-8e79-1e503ede1251)

It is simple and it does not imply OPeNDAP is ONLY for scientists.

@jgallagher59701 what do you think?

**Comment by jgallagher59701** [comment]
I think that is good.
