### ISSUE TITLE
Edit some items from the menu bars

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#46]
### Description

1) I think that `Presentations`, which currently lives under `Community`, belongs instead on `Documentation`.
2) `FAQs` currently under `Documentation`, should go under `Support`

**Comment by jgallagher59701** [comment]
I agree. Please make those changes. Thanks!

**Comment by Mikejmnez** [comment]
@jgallagher59701 Easy to move - ready.
