### ISSUE TITLE
OPeNDAP sends to outdated pydap ReadtheDocs

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#47]
### Description

`Pydap` is listed under `Software`, and a clickable image takes you to pydap's documentation. However, the URL is outdated since it takes you to an older version of the docs https://www.pydap.org/en/3.2.2/client.html.

Also - pydap has now a new icon. We should probably add it instead of the template there (see image below)

### Visual Aid

![Screenshot 2024-08-28 at 8 53 43 AM](https://github.com/user-attachments/assets/17f5e1ba-d4c4-4a83-ae1d-1ce278900829)

### Page URL 

https://www.opendap.org/software/

**Comment by jgallagher59701** [comment]
Yes. I agree. Please make those changes. Thanks!!

**Comment by Mikejmnez** [comment]
@jgallagher59701 done!
