### ISSUE TITLE
The link for the BES documentation is broken on the https://opendap.github.io/documentation/ site

### ISSUE THREAD

**Issue by jgallagher59701** [OPENDAP/Website#54]

**Comment by jgallagher59701** [comment]
The link is https://opendap.github.io/bes/html/. There is  bug in the BES's Makefile target that builds the on-line docs:

 ```
create mode 100644 html/tab_h.png
 create mode 100644 html/tab_s.png
 create mode 100644 html/tabs.css
remote: Permission to zeux/pugixml.git denied to jgallagher59701.
fatal: unable to access 'https://github.com/zeux/pugixml.git/': The requested URL returned error: 403
hyrax_git/bes % 

```

I might be able to fix this, but it seems that the libdap4 GH docs are also not working - not getting updated - and it seems the bui,d-gh-docs.sh scripts are different (slightly) for each of the two repos.

Debug and fix.

**Comment by Mikejmnez** [comment]
Very interesting. @jgallagher59701 I looked at this briefly. Is the BES documentation build with Office word documents? Should be upgrade to asciidocs? I now have experience building adoc files for OPeNDAP. 

SIDE note: Is this issue for the Website Project? Or the BES project?

**Comment by jgallagher59701** [comment]
These BES documents are built using Doxygen which is similar to Python's documentation comments. But, doxygen can build UML, etc. 

This is an issue for the BES project. libdap4 uses the same process to build it's online reference documentation and it appears to be working (https://opendap.github.io/libdap4/html/) albeit somewhat out-of-date.

**Comment by Mikejmnez** [comment]
> This is an issue for the BES project. libdap4 uses the same process to build it's online reference documentation and it appears to be working (https://opendap.github.io/libdap4/html/) albeit somewhat out-of-date.

Ok. Right now it is being listed under the `Website` Project. Will try to make the change

**Comment by jgallagher59701** [comment]
Let's close this - do you agree?

**Comment by Mikejmnez** [comment]
Sure - up to you. I moved this away from Website to the backlog of BES.
