### ISSUE TITLE
Hyrax release 1.17.0 has download binaries for hyrax 1.16.8

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#55]
### Description

Under the binary options for download on the [Hyrax-1.17](https://www.opendap.org/hyrax-1-17/) release post, the binaries made available for download for OLFS are the 1.18.13 versions. But these are associated with the hyrax-1.16.8 release. Instead the ones that need to be available for download are the 1.18.14 (see the [README](https://github.com/OPENDAP/hyrax-docker/blob/master/README.md)). libdap and bes are correct, only Olfs is incorrect (I even downloaded them and confirmed that the version is 1.18.13).

### Visual Aid

![Screenshot 2024-09-18 at 4 04 57 PM](https://github.com/user-attachments/assets/a07508ee-ddc9-40a7-9aaf-24d34576c51c)

**Comment by Mikejmnez** [comment]
@jgallagher59701 this is ready for review

**Comment by jgallagher59701** [comment]
Fixed. But, wow, the way the hyrax 1.16.x release plage is done is much better, I think.

**Comment by Mikejmnez** [comment]
Yes! I am going to  edit the Hyrax-1.17 to broadly match that of 1.16x
