### ISSUE TITLE
rename `Release` menu option to `Latest Release`

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#56]
### Description

Currently, the option `Release` takes the user to the Download Hyrax-1.17 page. And so it is intended as a `Take me to the latest release` navigation option, even though the name of this option is not clear.

### Visual Aid

![Screenshot 2024-09-18 at 6 07 20 PM](https://github.com/user-attachments/assets/b4413c68-90da-4b79-8fc7-f633acd767f5)

**Comment by Mikejmnez** [comment]
@jgallagher59701 ready for review

**Comment by jgallagher59701** [comment]
Thanks!
