### ISSUE TITLE
move `Not Seeing your question` to the top of FAQ page

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#57]
### Description

On the [FAQ](https://www.opendap.org/faq/), at the bottom there is a `Not seeing your question` that takes the person to the Discourse. It is possible that people miss it. Try moving it to the top!

**Comment by Mikejmnez** [comment]
@jgallagher59701 this is ready for review

**Comment by jgallagher59701** [comment]
Thamks!
