### ISSUE TITLE
Stats needed for the Website

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/Website#7]
### Description

The draft website has some "made up stats" on the main page. These "stats" are a placeholder for some real numbers that should reflect the long history that OPeNDAP has, and its leadership/impact when it comes to but not limited to open-source, data democratization, and open science. 

### Visual Aid

<img width="300" alt="Screenshot 2024-05-22 at 5 41 30 PM" src="https://github.com/OPENDAP/Website/assets/8241481/ddb9943e-9ffa-4f77-927e-ea55cddaadd4">

### Page URL 

**HOMEPAGE**

### Approach:

Write ideas below in the comments about stats that may be important for the site.

**Comment by Mikejmnez** [comment]
* **I suggest to keep the**  `30+ years`, but the rest should be replaced (these were simply made up as filler for the website)

**Comment by jgallagher59701** [comment]
Yeah, I saw that too. I think we have to work on stats.

**Comment by Mikejmnez** [comment]
@jgallagher59701 How about the following stats:

## a) **30+ years of experience**
Facilitating open data access

## b)  **14+ data handlers**
Flexible data format compatibility. 
[Source](https://newopendap.flywheelsites.com/software/hyrax-data-server/) 

##  c) **10+ access patterns**
Interoperability with other software libraries. 

[Source](https://newopendap.flywheelsites.com/software/software-from-other-sources/)
## d) **5+ distinct implementations**
Open source collaborations 

Source: (HYRAX, ERDAP, THREDDS, PyDAP, and i forget the name of other ones cited in the history of opendap. There's another one in python+rust that I forget the name.


## e) [missing value] data volume
available through opendap servers

(Don't have the source for data volumes available through opendap)

**Comment by Mikejmnez** [comment]
## about data volume:

I came up with the estimate ~ 10Petabytes as follows:

```python
#========
#  Typical access pattern for climatology data
#  Computing annual mean and anomalies over a decade for a
#  couple of surface field variables (monthly data), 
#  each ~ 10 Mbytes of uncompressed data
# ========

daily_users = 30  # conservative estimate of daily OPeNDAP users
volume_data_accessed = 30e9 #  ~ tens of gigabytes
days_in_year = 365
OPeNDAP_years = 30
total_volume = daily_users * volume_data_accessed * days_in_year*OPeNDAP_years
total_volume / 1e15
>>> 9.85
```

**Comment by Mikejmnez** [comment]
@jgallagher59701 ready for review...

**Comment by jgallagher59701** [comment]
Those seem like OK stats. As a bit of humor, you could add "1 official beverage" but only if you think that's OK.

**Comment by Mikejmnez** [comment]
I think perhaps we should leave that out, as an "internal stat" hahahaha
