### ISSUE TITLE
Homepage: Main text at the top of the page does not convert well to mobile phone version

### ISSUE THREAD

**Issue by Arika-V** [OPENDAP/Website#8]
Note that the main text moves off the photo and is not visible because of the white background. 

![Image](https://github.com/OPENDAP/Website/assets/170548569/3fd23a0c-bde3-4498-bb74-51e7393d6b8e)

https://newopendap.flywheelsites.com/

**Comment by Mikejmnez** [comment]
This issue only relates to the Mobile-friendly display of the website.

I changed the 'background color' to midnight (it was `white` or `cloud`) and it looks better now. The website looks the same for web browser size larger than the `mobile friendly size`. For smaller sizes (mobile friendly size), the top of the home page now looks like this:




![Image](https://github.com/OPENDAP/Website/assets/8241481/4519454a-a2de-4fb0-abee-d0901d7b46fa)

**Comment by Mikejmnez** [comment]
@jgallagher59701 this is ready for review

**Comment by jgallagher59701** [comment]
I think this is fixed.
