### ISSUE TITLE
Homepage: Stat numbers overlap with illustration when screen size is not full size

### ISSUE THREAD

**Issue by Arika-V** [OPENDAP/Website#9]
Note the overlap of the text and the dark image of the illustration.  https://newopendap.flywheelsites.com/ 

![Image](https://github.com/OPENDAP/Website/assets/170548569/11928b4f-40d4-48af-8fb2-f77c97c780c7)

**Comment by Mikejmnez** [comment]
I tested this, and the snapshot above shows the smallest browser size before the website transitions to a mobile friendly view (by manually reducing the size of the browser). On my iPad there is no overlap (standard framesize), and there is no overlap either in the mobile friendly view.

@jahattox, is there a place in WordPress where can one manually set a size at which the website transitions to mobile friendly view? I think the overlap will depend on the amount of text, but it would be nice to know how, if possible, how to customize the website behaviors with respect to browser size.

**Comment by jahattox** [comment]
@Mikejmnez I adjusted this to fix the issue. After clearing your cache, how do things look on your end?

You can edit the styles by creating CSS overrides if you like. However, that tends to be somewhat error-prone. The way it's coded, there shouldn't be any text/image overlap for most normal use cases (i.e. it should look good unless you drastically increase the amount of text in the columns).

**Comment by Mikejmnez** [comment]
@jahattox it works. Thanks!
